# Generated by Django 4.1.3 on 2022-11-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('religion', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('fname', models.CharField(max_length=255)),
                ('fphone', models.CharField(max_length=255)),
                ('femail', models.EmailField(max_length=255)),
                ('foccupation', models.CharField(max_length=255)),
                ('mname', models.CharField(max_length=255)),
                ('mphone', models.CharField(max_length=255)),
                ('memail', models.EmailField(max_length=255)),
                ('moccupation', models.CharField(max_length=255)),
                ('admdate', models.CharField(max_length=255)),
                ('schoolname', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('refno', models.CharField(max_length=255)),
            ],
        ),
    ]
