# Generated by Django 4.1.3 on 2022-11-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_admissions_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissions',
            name='course',
            field=models.CharField(default='BBIT', max_length=255),
            preserve_default=False,
        ),
    ]
